# Generated by Django 3.1.7 on 2021-08-11 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210811_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='date',
            new_name='created_at',
        ),
    ]
